### ISSUE TITLE
Feature Request: setDefaultStrategy then createOrUpdate

### ISSUE THREAD

**Issue by JR-Utily** [yaacovCR/angular-stored-object#3]
as discussed with Yaacov:
> In theory, a combined method could be used that creates
> or updates as necessary and use a default storage strategy, that is perhaps
> specified when the service is created. I think this is a reasonable feature
> request, especially useful when the storage strategy is not likely to
> change.

**Comment by yaacovCR** [comment]
Fixed by:
https://github.com/yaacovCR/angular-stored-object/commit/a6da5f5e6b186e0c861ab0355fe6db10126067d2
https://github.com/yaacovCR/angular-stored-object/commit/aece42da5ecf6eaac80d0e9f0a0ecd1d1432e816

**Comment by yaacovCR** [comment]
Please let me know if this does not work for you.
