### ISSUE TITLE
_setup and __loadIntoMemory are inconsistent

### ISSUE THREAD

**Issue by JR-Utily** [yaacovCR/angular-stored-object#4]
in _loadIntoMemory method, we have
` _storageType = (_storageStrategy === 'localStrategy') ? 'localStorage' : 'sessionStorage';`
while in _setup we have 
`_storageType = (storageStrategy === 'localStorage') ? 'localStorage' : 'sessionStorage';`

I think this 'localStrategy' in loadIntoMemory is messing with things, and so it results after a reload in having in sessionStorage things meant to be in localStorage

**Comment by yaacovCR** [comment]
Could be there is a bug, I will try to see if I can duplicate, but that
code seeking discrepancy is actually because _setup is responsible for
signing to variable _storageStrategy and so the values are equivalent.
Unless you are talking about a discrepancy I am not noticing, ie not the
underscore?

**Comment by JR-Utily** [comment]
The string 'localStrategy' is never used, it should be 'localStorage'
In fact, 'localStrategy' appears just on this line, so the test will always be false :)

I have tested on local to replace 'localStrategy' by 'localStorage' and it works fine

**Comment by yaacovCR** [comment]
Ah got it thank you

**Comment by yaacovCR** [comment]
I will patch this hopefully later today. Right now, I am trying to figure out why the tests don't pick it up, let me know if you see the error. After, I get the tests to fail, I will fix the typo.

**Comment by yaacovCR** [comment]
Thanks for spotting this, hope this helps.
